name: RSS Aggregator

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  aggregate_rss_feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Set up Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install feedparser lxml

    - name: Run RSS aggregator script
      run: |
        python rss_aggregator.py
        echo "::set-env name=RSS_FEED_ENTRIES::${{ env.RSS_FEED_ENTRIES }}"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
