name: RSS Aggregator

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  aggregate_rss_feeds:
    runs-on: ubuntu-latest

    steps:
    - name: Start
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install feedparser lxml
        touch .env 

    - name: Run RSS aggregator script
      env:
        GITHUB_ENV: .env
      run: |
        python rss_aggregator.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.MY_GH_TOKEN }}
        publish_dir: ./
        publish_branch: main
