name: RSS Aggregator

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every 1 hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  aggregate_rss_feeds:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Start
      uses: actions/checkout@v3

    # - name: Setup node
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install feedparser lxml beautifulsoup4
        touch .env

    - name: Run RSS aggregator script
      env:
        GITHUB_ENV: .env
      run: |
        python rss_aggregator.py

    - name: Update processed links file
      run: |
      cat processed_links.txt >> history_processed_links.txt
      sort -u history_processed_links.txt > temp_processed_links.txt
      awk -F ' ' -v d="$(date -u --date="365 days ago" +%Y-%m-%dT%H:%M:%S)" '$1 > d' temp_processed_links.txt > processed_links.txt
      rm temp_processed_links.txt
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1

    - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        add: '.'
        #default_author: github_actor
        #fetch: false

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: 'feat: RSS feed update'

        # Arguments for the git pull command. By default, the action does not pull.
        # Default: ''
        #pull: '--rebase --autostash ...'

        # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
        # Default: true
        push: true